Module2 task1
htmlacademy-adaptive/1997457-cat-energy-25 pull request #2
Opened 2022-04-08 11:41 UTC by popovre

Сделал базовую разметку с намеком на бэм, для мобильной версии главной страницы

2022-04-09 11:06 UTC, summertime-fms requested changes
По разметке нет вопросов, но есть вопросы по БЭМу. ПОревьюил половину страницы чтобы не перегружать тебя сразу. После добьем вторую половину. С чем надо поработать 
1. Названия классов. Зачастую они слишком длинные. Будет заморочно писать стили. По возможности лучше сократить.
2. Создаешь очень много блоков по БЭМу. Там где это просто элементы. Блок - либо секция, либо переисползуемый компонент. Если на вопрос - а может ли этот элемент быть выдернут ищз этого места и переиспользован где то еще - ты отвечаешь вряд ли, то это не блок, а элемент. 

Окончательно БЭМ понимают только когда начинают стилизовать и собирать новые страницы на основе уже собранных => приходит с опытом. Поработай над комментариями оставленными мною здесь и в телеграмме и если что то непонятно то можем созвониться обсудить

2022-04-09 11:06 UTC, summertime-fms commented on source/index.html
> +<html class="page" lang="ru">
Зачастую в этом классе нет необходимости. Можно стилизовать по тегу.

2022-04-09 11:06 UTC, summertime-fms commented on source/index.html
> +    <div class="page__background">
А зачем для фона отдельный див?

2022-04-09 11:06 UTC, summertime-fms commented on source/index.html
> +        <div class="main-header__logo-icon-wrapper">
Старайся писать классы лаконичнее. Так будет проще

2022-04-09 11:06 UTC, summertime-fms commented on source/index.html
> +        <a class="main-header__logo-title main-header-title" href="index.html">
Я не думаю что стоит выносить попись в логотипе в отдельный бэмовский блок. Вряд ли это переиспользоваться будет

2022-04-09 11:06 UTC, summertime-fms commented on source/index.html
> +      <main class="main-main">
Это как?) Тут вообще можно не делать класс.

2022-04-09 11:06 UTC, summertime-fms commented on source/index.html
> +          <section class="main-container__subject subject">
По этой секции отписал в тг

2022-04-09 11:06 UTC, summertime-fms commented on source/index.html
> +          <section class="main-container__program program">
Давай уберем в секция класс от main-container.

2022-04-09 11:06 UTC, summertime-fms commented on source/index.html
> +            <div class="program-wrapper">
Кажется, ты имел ввиду program__wrapper

2022-04-09 11:06 UTC, summertime-fms commented on source/index.html
> +              <button class="button program-wrapper__choose-button program-choose-button">
Удачный микс, но к чему третий класс-блок?

2022-04-09 11:06 UTC, summertime-fms commented on source/index.html
> +              <ul class="program-wrapper__program-list program-list">
Усложняешь названия классов. зачем второй раз писать слово program? Можно просто program__list

2022-04-09 11:06 UTC, summertime-fms commented on source/index.html
> +              <ul class="program-wrapper__program-list program-list">
И зачем миксуешь? Разве будет подобный список где то еще переисползоваться? кажется, нет

2022-04-09 11:06 UTC, summertime-fms commented on source/index.html
> +              <ul class="program-wrapper__program-list program-list">
Пунктам списка аналогично мало смысла задавать класс-блок

2022-04-12 13:23 UTC, popovre commented on source/index.html
> +              <button class="button program-wrapper__choose-button program-choose-button">
Класс-блок? я просто хочу кнопку инивидуально стилизовать, но я удалил этот класс, буду использовать просто button

2022-04-12 13:23 UTC, popovre commented on source/index.html
> +          <section class="main-container__program program">
Убрал у всех секций

2022-04-12 13:26 UTC, popovre commented on source/index.html
> +              <button class="button program-wrapper__choose-button program-choose-button">
Я понимаю, что микс - это для переиспользования в разных разрешениях (типа телефон-десктоп)? В данном случае я хотел просто по третьему классу какие то визуальные отличия сделать (может размер отличается от других версий или еще что)

2022-04-12 13:32 UTC, popovre commented on source/index.html
> +              <ul class="program-wrapper__program-list program-list">
Кажется надо на строке сделать списку 2 класса по БЭМ: 1-й:: список, как элемент по БЭМ (program__list), 2-й:: список, как блок по БЭМ (program-list)? Я так примерно делал в дз, такая логика была.

2022-04-12 13:32 UTC, popovre commented on source/index.html
> +              <ul class="program-wrapper__program-list program-list">
Про микс не понял(

2022-04-12 15:15 UTC, summertime-fms commented on source/index.html
> +              <button class="button program-wrapper__choose-button program-choose-button">
микс это когда элемент одновременно является элементом от блока (program-wrapper__choose-button) и в то же время он - самостоятельный блок ( button ) Такой подход позволяет отделить повторяющееся от индивидуального и сократить количество стилей. Тут то, что ты хотел вынести в класс program-choose-button лучше оставить в классе-элементе

2022-04-12 15:19 UTC, summertime-fms commented on source/index.html
> +              <ul class="program-wrapper__program-list program-list">
Ты все верно понял. Только в блок обычно выносится то что будет переиспользваться где то еще. Кокретно список вряд ли будет переиспользоваться. Секция в которой он лежит - возможно, пункт списка - тоже вряд ли будет где то еще кроме как в этой секции. А раз этот блок будет переиспользоваться только как целостная секция - можно все подчинить ей. Писать классы от program__ и не париться. Если все еще непонятно, то ты можешь оставить, это не будет ошибкой при защите. В конце концов окончательное понимание как составить разметку по бэму приходит когда погружаешься в написание стилей и составлению страницы из готовых компонентов, так что это нормально)

2022-04-12 15:35 UTC, summertime-fms commented on source/index.html
> +      <a class="main-header-title-link" href="index.html">
Наверное main-header__title-link ты хотел сделать?

2022-04-12 15:35 UTC, summertime-fms commented on source/index.html
> +        <button class="button program__choose-button">
По ТЗ это ссылка. Ведет на страницу формы

2022-04-12 15:35 UTC, summertime-fms commented on source/index.html
> +      <section class="program">
Не кажется ли тебе, что секции вот [так](https://skr.sh/sDQRKrYPaU7) логичнее сделать? Кнопка принадлежит преыдущей секции.

2022-04-12 15:35 UTC, summertime-fms commented on source/index.html
> +            <a class="program-item__program-link" href="catalog.html">
Внимательно ТЗ. Эти ссылки ведут на разделы каталога, а значит хреф должен быть другим.

2022-04-12 15:35 UTC, summertime-fms commented on source/index.html
> +          <li class="specification-list__item specification-item specification-function">
Тут скорее модификаторы будут уместны а не добавление блока ( я про третий класс). Получится что то вроде specification-list__item specification-list__item--function. Модификатор модифицирует что то конкретное одно. Тут как раз так и будет - иконка меняется в квадратике и только

2022-04-12 15:35 UTC, summertime-fms commented on source/index.html
> +        <p class="example__cost cost-description">
Нет необходимости выносить в отдельный блок. Первого класса будет вполне достаточно

2022-04-12 15:35 UTC, summertime-fms commented on source/index.html
> +            <p class="invite-description__text adress">
address, не забываем)

2022-04-13 03:36 UTC, popovre commented on source/index.html
> +              <ul class="program-wrapper__program-list program-list">
Миша, то есть в принципе все классы должны быть написаны по БЭМ, он либо БЛОК, либо например ЭЛЕМЕНТ и если он НЕ переиспользуется, то мы ему ВСЕ стили: визуальные(цвет, шрифт и проч) и позиционирование пишем в один селектор по классу БЭМ?

2022-04-13 03:37 UTC, popovre commented on source/index.html
> +              <ul class="program-wrapper__program-list program-list">
А если переиспользуется, то мы его делаем БЛОКОМ допом. То есть хватает 2-х селекторов для полного счастья?

2022-04-13 03:38 UTC, popovre commented on source/index.html
> +      <section class="program">
согласен, я кажется так и хотел, не знаю как прошляпил, вроде акцентировал на этом внимание

2022-04-13 03:48 UTC, popovre commented on source/index.html
> +              <ul class="program-wrapper__program-list program-list">
А что делать если у какой то например ссылки родитель не переиспользуемый и у родителя написан один класс типа: "block__element". Тогда у потомка ссылки какой должен быть класс, можно написать просто класс через дефис "something-link?"- но тогда мы сделали его просто блоком получается, или не блоком?

2022-04-13 06:15 UTC, popovre commented on source/index.html
> +            <p class="invite-description__text adress">
А я же написал адрес) Исправил слово

2022-04-13 06:16 UTC, popovre commented on source/index.html
> +        <button class="button program__choose-button">
готово

2022-04-13 06:16 UTC, popovre commented on source/index.html
> +      <a class="main-header-title-link" href="index.html">
Точно

2022-04-13 08:47 UTC, merged

2022-04-13 08:48 UTC, summertime-fms commented on source/index.html
> +            <p class="invite-description__text adress">
Имел ввиду тег <address>

2022-04-13 08:51 UTC, summertime-fms commented on source/index.html
> +              <ul class="program-wrapper__program-list program-list">
Проще будет объяснить так. Ты дробишь страницу на крупные блоки - шапка, подвал, секции. Это все будет блоками по бэму. Внутри могут быть менее крупные блоки (например навигация может быть в шапке и одновременно в футере). А может и не быть. Если ты объявляешь блок и внутри него лежит что то переиспользуемое, хотя сам блок НЕ переиспользуемое можно этому чему то задать блок. В Тг скину пример.

2022-04-13 08:51 UTC, summertime-fms commented on source/index.html
> +              <ul class="program-wrapper__program-list program-list">
Ты залез в тонкости😁

2022-04-13 11:40 UTC, popovre commented on source/index.html
> +              <ul class="program-wrapper__program-list program-list">
А как не задать блок, а просто придумать как раньше класс-нейтральный, чтобы просто стилизовать? Как их называть то?)