Module3-task1
htmlacademy-adaptive/1997457-cat-energy-25 pull request #4
Opened 2022-04-21 23:14 UTC by popovre

Не смог подключить переменную(бэкграунд), объявленную в одном файле к другому файлу (body-container) Или так нельзя?

2022-04-22 07:12 UTC, summertime-fms commented on source/form.html
> +      <img class="invite-map__img" src="/source/img/mobile/index/invite-map.jpg" width="320" height="362" alt="ул. Большая Конюшенная, д. 19/8 Санкт-Петербург">
А чего пути не отредачил?

2022-04-22 07:12 UTC, summertime-fms commented on source/sass/fonts.scss
> +@font-face {
Потом не забудь подключить еще Bold

2022-04-22 07:12 UTC, summertime-fms commented on source/sass/hidden.scss
> +.visually-hidden {
либо переименуй файл так чтобы он совпадал с название класса-блока либюо просто закинь этот селектор в utils.scss

2022-04-22 07:12 UTC, summertime-fms commented on source/sass/img.scss
> +  display: inline-block;
Если задать block то кажется не понадобится вертикальное выравнивание

2022-04-22 07:12 UTC, summertime-fms commented on source/sass/index/page.scss
> +  font-family: "Oswald", "sans-serif", "Big Caslon";
Порядок неверный. sans-serif в самом конце

2022-04-22 07:12 UTC, summertime-fms commented on source/sass/style.scss
> +@use "mixins.scss";
Расширение можно не писать

2022-04-25 05:59 UTC, summertime-fms requested changes
Слишком много фикс. значений. Надо стараться избегать подобного. (я не говорю про случаи когда это мелкие декоративные элементы а-ля квадратики и кружочки)

2022-04-25 05:59 UTC, summertime-fms commented on source/sass/catalog/additional.scss
> +  min-height: 964px;
Что то кажется мне нет необходимости в этом свойстве

2022-04-25 05:59 UTC, summertime-fms commented on source/sass/catalog/additional.scss
> +    line-height: 24px;
line-height: 1; так будет лучше и проще при адаптиве. высота строки автоматически будет рассчитываться от текущего размера шрифта

2022-04-25 05:59 UTC, summertime-fms commented on source/sass/catalog/additional.scss
> +    color: var(default-black);
тут синтаксис использования кастомного свойства неверный. var(--property);

2022-04-25 05:59 UTC, summertime-fms commented on source/sass/catalog/additional.scss
> +    font-family: "Arial";
Отсутствуют запасные шрифты. sans-serif хотя бы. А вообще можно вынести  кастомное свойство

2022-04-25 05:59 UTC, summertime-fms commented on source/sass/catalog/additional.scss
> +    font-family: "Arial";
везде поправить

2022-04-25 05:59 UTC, summertime-fms commented on source/sass/catalog/additional.scss
> +    width: 62px;
С кнопками не используем фиксированные величины.

2022-04-25 05:59 UTC, summertime-fms commented on source/sass/catalog/additional.scss
> +    top: 0;
Есть [способ](https://doka.guide/css/inset/) поизящнее. Убери ширину и высоту и задай inset: 0;

2022-04-25 05:59 UTC, summertime-fms commented on source/sass/catalog/products.scss
> +  grid-template-columns: auto;
Одноколончатый грид - это как? Это же получается просто обычный поток документа без всяких сеток

2022-04-25 05:59 UTC, summertime-fms commented on source/sass/catalog/products.scss
> +    width: 258px;
Такое тоже не очень хорошо делать. Хотя бы в процентах давай, чтобы при увеличении гирины экрана текст расправлялся.

2022-04-25 13:24 UTC, popovre commented on source/sass/catalog/products.scss
> +  grid-template-columns: auto;
я думал он автоматически подберет таким образом число колонок, надо менять на автоподбор числа колонок.

2022-04-26 20:13 UTC, merged